name: Vendo arquivos compartilhados entre Jobs

on:
  push:
    branches:
      - main

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Confere versão do ubuntu
        run: cat /etc/os-release

      - name: Exibir uma mensagem
        run: echo "Estou fazendo o curso de Github Actions da Linuxtips" > mensagem.txt

  job_2:
    runs-on: ubuntu-latest
    steps:
      - name: Exibe arquivos do diretório
        run: ls -lha

      - name: Acessa arquivo mensagem
        run: cat mensagem.txt